Repository qexat/Babble, pull requests merged in 2024-01, with the labels that each got.

#1 Refactor the application
  babble/babble.py
  babble/builtins/_themes.py
  babble/cli.py
  babble/funcs.py
  babble/tuilib/__init__.py
  babble/tuilib/app.py
  babble/tuilib/context.py
  babble/tuilib/renderer.py
  babble/tuilib/themes.py
  babble/tuilib/util.py
  babble/tuilib/window.py
Labels: enhancement

#3 GH-2: Fix random fill interruption not being correctly handled
  babble/babble.py
  babble/tuilib/app.py
  babble/tuilib/context.py
Labels: bug

#4 Minor refactorings
  babble/babble.py
  babble/tuilib/app.py
Labels: enhancement

#7 Fix window copy
  src/babble/tuilib/window.py
Labels: bug

#9 Added Windows support
  pyproject.toml
Labels: enhancement

#12 Fix outdated README
  README.md
Labels: documentation

#13 GH-11: README: use built-in `venv` instead of `virtualenv`
  README.md
Labels: documentation
